### ISSUE TITLE
THUNDER RUNNER

### ISSUE THREAD

**Issue by Rinnegatamante** [Rinnegatamante/YoYo-Loader-Vita-Compatibility#8]
# Game summary
- Game name: THUNDER RUNNER
- Game version: v.1.0.6

# YoYo Loader summary
- Version: vDebug

# Issues
In game the renderer is not fullscreen, may be cause the game forces portrait mode.

# Screenshots
![immagine](https://user-images.githubusercontent.com/9152710/162085904-bc95d784-f8dc-4626-b40e-2f0ab45ee2e1.png)
![immagine](https://user-images.githubusercontent.com/9152710/162085917-8f5b2314-ad38-4ce0-9e35-ec332afb4b41.png)

**Comment by Rinnegatamante** [comment]
Fixed, now renders perfectly

![immagine](https://user-images.githubusercontent.com/9152710/162089631-b78319ca-d512-4f1a-97db-35b57aa4b3c6.png)

**Comment by SofyUchiha** [comment]
@Rinnegatamante The same problem is back: 
![image](https://user-images.githubusercontent.com/70182567/163124262-f23ebefa-6364-433c-b912-e4562113aacf.png)
![image](https://user-images.githubusercontent.com/70182567/163124315-2d46dce6-9164-4a86-8922-41f44bc9fcbd.png)

Yoyo-Loader v [76ab311](https://github.com/Rinnegatamante/yoyoloader_vita/commit/76ab311c6e4532f9f538bc24312d4cd7ebc84a79)

**Comment by Rinnegatamante** [comment]
Renders still fine here...
![immagine](https://user-images.githubusercontent.com/9152710/163130755-dcfaa3a3-764b-4f3b-83cd-95e6ecf36e4c.png)

**Comment by SofyUchiha** [comment]
Do you use some kind of configuration before running the game?

**Comment by Rinnegatamante** [comment]
Debug Mode On

**Comment by SofyUchiha** [comment]
Okey, ty ❤️

**Comment by Rinnegatamante** [comment]
There seems to be some minor issues with pause menu indeed but in game, it renders fine.

**Comment by SofyUchiha** [comment]
@Rinnegatamante Crash randomly after the last commit: [776de88]
[yyl.log](https://github.com/Rinnegatamante/YoYo-Loader-Vita-Compatibility/files/8536053/yyl.log)

**Comment by SofyUchiha** [comment]
> @Rinnegatamante The same problem is back: ![image](https://user-images.githubusercontent.com/70182567/163124262-f23ebefa-6364-433c-b912-e4562113aacf.png) ![image](https://user-images.githubusercontent.com/70182567/163124315-2d46dce6-9164-4a86-8922-41f44bc9fcbd.png)
> 
> Yoyo-Loader v [76ab311](https://github.com/Rinnegatamante/yoyoloader_vita/commit/76ab311c6e4532f9f538bc24312d4cd7ebc84a79)

@Rinnegatamante The game continues to have this bug, but with the Assets Externalization, it no longer crashes, so it's playable.

**Comment by BrickCrypt** [comment]
@Rinnegatamante Currently it works fine without any rendering problem
![2022-09-30-144445](https://user-images.githubusercontent.com/104641878/193345355-31f08ae2-158e-4883-be43-94e17c4ea4fd.jpg)
Playable and enable Fake Windows

keys.ini is more optional if you prefer to play with LR shoulders
**CROSS=A
SQUARE=K
UP=A
DOWN=K
LANALOG=ON
R1=A
L1=K**
